# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Coral Project
tagline:             '~'
description:         'Design'
url:                 https://github.com/coralproject/design
baseurl:             'https://github.com/coralproject/design'
paginate:            5

# About/contact
author:              
  name:              Angel
  url:               https://github.com/coralproject/design
  email:             angel@mozillafoundation.org

# Custom vars
version:             1.0.0
mygithub:            https://github.com/coralproject/
repo:                design