# Site settings
title: Style guide template
email: angel@mozillafoundation.org
description: Pattern Library
baseurl: ""
url: "http://coralproject.github.io/design/pattern-library" # the base hostname & protocol for your site
twitter_username: coralproject
github_username:  coralproject

# Collections
collections:
  components:
    output: false

# Front Matter Defaults

# General settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
sass:
  sass_dir: _sass
  style: :compressed
